name: Request Infra

on:
  push:
    branches:
      - main

jobs:
  call-terraform:
    uses: yashwanthss18/terraform-azure-sql/.github/workflows/terraform.yml@main

    secrets:
        secrets: inherit

      
