name: Request Infra

on:
  push:
    branches:
      - main

jobs:
  call-terraform:
    uses: yashwanthss18/terraform-azure-sql/.github/workflows/terraform.yml@main

    with:
      sql_server_name: client-sql-server
      database_name: clientdb
      location: Central India
